# Generated by Django 4.0 on 2022-01-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
